import type { Metadata } from "next";
import "./globals.css";
import favicon from "../public/favicon.ico";
import { AppProps } from 'next/app';
import { DataProvider } from "../contexts/DataContext";


export const metadata: Metadata = {
  title: "DSEU ERP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href={favicon.src} />
      </head>
      <body><DataProvider>{children}</DataProvider></body>
    </html>
  );
}
