import type { Metadata } from "next";
import "./globals.css";
import favicon from "../public/favicon.ico";

export const metadata: Metadata = {
  title: "DSEU ERP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* <script src="https://cdnjs.cloudflare.com/ajax/libs/react/16.6.3/umd/react.production.min.js" async ></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/react-dom/16.6.3/umd/react-dom.production.min.js" async ></script> */}
        <link rel="icon" href={favicon.src} />
      </head>
      <body>{children}</body>
    </html>
  );
}
