import type { Metadata } from "next";
import "./globals.css";
import favicon from "../public/favicon.ico"



export const metadata: Metadata = {
  title: "DSEU ERP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"> 
      <head>
      <link
            rel="icon"
            href={favicon.src}
        />
        </head>     
      <body>{children}</body>      
    </html>
  );
}
